/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/avatarNew.glb -K -k 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/avatarNew.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-0.162, 0.225, -0.863]} rotation={[-Math.PI, 0.567, -Math.PI]}>
          <group name="Armature002" position={[0, 0.023, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes.mixamorigHips} />
          </group>
          <skinnedMesh name="EyeLeft001" geometry={nodes.EyeLeft001.geometry} material={materials['Wolf3D_Eye.004']} skeleton={nodes.EyeLeft001.skeleton} />
          <skinnedMesh name="EyeRight001" geometry={nodes.EyeRight001.geometry} material={materials['Wolf3D_Eye.005']} skeleton={nodes.EyeRight001.skeleton} />
          <skinnedMesh name="Wolf3D_Body001" geometry={nodes.Wolf3D_Body001.geometry} material={materials['Wolf3D_Body.002']} skeleton={nodes.Wolf3D_Body001.skeleton} />
          <skinnedMesh name="Wolf3D_Glasses001" geometry={nodes.Wolf3D_Glasses001.geometry} material={materials['Wolf3D_Glasses.002']} skeleton={nodes.Wolf3D_Glasses001.skeleton} />
          <skinnedMesh name="Wolf3D_Hair001" geometry={nodes.Wolf3D_Hair001.geometry} material={materials['Wolf3D_Hair.002']} skeleton={nodes.Wolf3D_Hair001.skeleton} />
          <skinnedMesh name="Wolf3D_Head001" geometry={nodes.Wolf3D_Head001.geometry} material={materials['Wolf3D_Skin.002']} skeleton={nodes.Wolf3D_Head001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom001" geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials['Wolf3D_Outfit_Bottom.002']} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear001" geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials['Wolf3D_Outfit_Footwear.002']} skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top001" geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Wolf3D_Outfit_Top.002']} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
          <skinnedMesh name="Wolf3D_Teeth001" geometry={nodes.Wolf3D_Teeth001.geometry} material={materials['Wolf3D_Teeth.002']} skeleton={nodes.Wolf3D_Teeth001.skeleton} />
        </group>
        <group name="Desk" position={[-0.074, 0, -1.521]} rotation={[0, -1.571, 0]}>
          <mesh name="Plane001_Plane002_BlackWood001" geometry={nodes.Plane001_Plane002_BlackWood001.geometry} material={materials['BlackWood.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_1" geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry} material={materials['BlackCoatSteel.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_2" geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry} material={materials['GrayPlastic.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_3" geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry} material={materials['WhiteSteelScrew.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_4" geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry} material={materials['BlackPlastic.001']} />
        </group>
        <group name="SM_ShelfSM_Shelf1" position={[-0.868, 1.694, -1.994]}>
          <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={materials.lambert2SG} />
          <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={materials['795548.001']} />
        </group>
        <group name="LavaLamp" position={[-1.302, 2.071, -1.986]}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials.lambert4SG} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['lambert2SG.001']} />
          <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={materials['lambert3SG.002']} />
        </group>
        <mesh name="WawaRug" geometry={nodes.WawaRug.geometry} material={materials.Rug} position={[-0.281, 0.009, 0.765]} />
        <group name="keyboard" position={[-0.053, 0.981, -1.316]} rotation={[0.106, -0.208, -0.069]} scale={0.647}>
          <mesh name="mesh425587018" geometry={nodes.mesh425587018.geometry} material={materials['mat21.004']} />
          <mesh name="mesh425587018_1" geometry={nodes.mesh425587018_1.geometry} material={materials['mat22.001']} />
          <mesh name="mesh425587018_2" geometry={nodes.mesh425587018_2.geometry} material={materials['mat9.002']} />
          <mesh name="mesh425587018_3" geometry={nodes.mesh425587018_3.geometry} material={materials['mat16.001']} />
        </group>
        <group name="iMac" position={[0.454, 0.939, -1.723]} rotation={[Math.PI, -1.099, Math.PI]}>
          <mesh name="iMac_1" geometry={nodes.iMac_1.geometry} material={materials.Screen} />
          <mesh name="iMac_1_1" geometry={nodes.iMac_1_1.geometry} material={materials.ScreenBlack} />
          <mesh name="iMac_1_2" geometry={nodes.iMac_1_2.geometry} material={materials.iMacBody} />
        </group>
        <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={materials['lambert3SG.003']} position={[-0.137, 0.204, -0.251]} scale={0.79} />
        <group name="plant" position={[-0.78, 1.071, -1.576]}>
          <mesh name="mesh24448074" geometry={nodes.mesh24448074.geometry} material={materials['mat9.003']} />
          <mesh name="mesh24448074_1" geometry={nodes.mesh24448074_1.geometry} material={materials['mat20.001']} />
          <mesh name="mesh24448074_2" geometry={nodes.mesh24448074_2.geometry} material={materials['mat21.005']} />
        </group>
        <group name="Chair" position={[-0.278, -0.031, -0.708]} rotation={[0, -0.376, 0]} scale={[0.906, 1.04, 0.906]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
        </group>
        <group name="Plane">
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Floor} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.White} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.Wall} />
          <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials.Glass} />
        </group>
        <group name="Houseplant_7" position={[-2.497, 1.025, -1.063]} rotation={[0, 1.571, 0]}>
          <mesh name="Houseplant_7001" geometry={nodes.Houseplant_7001.geometry} material={materials['mat14.001']} />
          <mesh name="Houseplant_7001_1" geometry={nodes.Houseplant_7001_1.geometry} material={materials.mat20} />
          <mesh name="Houseplant_7001_2" geometry={nodes.Houseplant_7001_2.geometry} material={materials['mat13.001']} />
          <mesh name="Houseplant_7001_3" geometry={nodes.Houseplant_7001_3.geometry} material={materials['mat11.001']} />
          <mesh name="Houseplant_7001_4" geometry={nodes.Houseplant_7001_4.geometry} material={materials.mat9} />
          <mesh name="Houseplant_7001_5" geometry={nodes.Houseplant_7001_5.geometry} material={materials.mat10} />
          <mesh name="Houseplant_7001_6" geometry={nodes.Houseplant_7001_6.geometry} material={materials.mat8} />
          <mesh name="Houseplant_7001_7" geometry={nodes.Houseplant_7001_7.geometry} material={materials.mat0} />
          <mesh name="Houseplant_7001_8" geometry={nodes.Houseplant_7001_8.geometry} material={materials.mat12} />
          <mesh name="Houseplant_7001_9" geometry={nodes.Houseplant_7001_9.geometry} material={materials.mat18} />
          <mesh name="Houseplant_7001_10" geometry={nodes.Houseplant_7001_10.geometry} material={materials.mat19} />
          <mesh name="Houseplant_7001_11" geometry={nodes.Houseplant_7001_11.geometry} material={materials.mat22} />
          <mesh name="Houseplant_7001_12" geometry={nodes.Houseplant_7001_12.geometry} material={materials.mat15} />
          <mesh name="Houseplant_7001_13" geometry={nodes.Houseplant_7001_13.geometry} material={materials.mat23} />
          <mesh name="Houseplant_7001_14" geometry={nodes.Houseplant_7001_14.geometry} material={materials.mat16} />
          <mesh name="Houseplant_7001_15" geometry={nodes.Houseplant_7001_15.geometry} material={materials.mat3} />
          <mesh name="Houseplant_7001_16" geometry={nodes.Houseplant_7001_16.geometry} material={materials.mat17} />
          <mesh name="Houseplant_7001_17" geometry={nodes.Houseplant_7001_17.geometry} material={materials.mat5} />
          <mesh name="Houseplant_7001_18" geometry={nodes.Houseplant_7001_18.geometry} material={materials.mat6} />
        </group>
        <group name="Laptop" position={[-0.145, 0.98, -1.854]} scale={0.161}>
          <mesh name="Laptop_1" geometry={nodes.Laptop_1.geometry} material={materials['mat16.002']} />
          <mesh name="Laptop_2" geometry={nodes.Laptop_2.geometry} material={materials['mat23.002']} />
          <mesh name="Laptop_3" geometry={nodes.Laptop_3.geometry} material={materials['mat17.001']} />
          <mesh name="Laptop_4" geometry={nodes.Laptop_4.geometry} material={materials['mat15.001']} />
          <mesh name="Laptop_5" geometry={nodes.Laptop_5.geometry} material={materials.mat25} />
        </group>
        <mesh name="polySurface5" geometry={nodes.polySurface5.geometry} material={materials.blinn5SG} position={[-0.463, 1.978, -1.858]} rotation={[Math.PI / 2, 0, 0.999]} scale={-0.001} />
      </group>
    </group>
  )
}

useGLTF.preload('/avatarNew.glb')
