/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/roomnew.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MyOffice(props) {
    const { nodes, materials } = useGLTF("models/roomnew.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.pPlane1_Mesh_CatTree1.geometry}
                material={materials.aiStandardSurface1SG}
                position={[-2.215, 0, 1.536]}
                rotation={[0, 1.571, 0]}
                scale={0.202}
            />
            <mesh
                geometry={nodes.cat_立方体009.geometry}
                material={materials.vertex}
                position={[-2.053, 0.696, 1.654]}
                rotation={[0, 1.571, 0]}
                scale={0.345}
            />
            <group position={[-0.521, 2.166, -2.023]} scale={0.521}>
                <mesh
                    geometry={nodes.mesh372063805.geometry}
                    material={materials["mat23.003"]}
                />
                <mesh
                    geometry={nodes.mesh372063805_1.geometry}
                    material={materials.mat24}
                />
                <mesh
                    geometry={nodes.mesh372063805_2.geometry}
                    material={materials["mat22.002"]}
                />
                <mesh
                    geometry={nodes.mesh372063805_3.geometry}
                    material={materials["mat20.002"]}
                />
                <mesh
                    geometry={nodes.mesh372063805_4.geometry}
                    material={materials.mat7}
                />
                <mesh
                    geometry={nodes.mesh372063805_5.geometry}
                    material={materials["mat10.001"]}
                />
                <mesh
                    geometry={nodes.mesh372063805_6.geometry}
                    material={materials["mat9.001"]}
                />
                <mesh
                    geometry={nodes.mesh372063805_7.geometry}
                    material={materials["mat17.002"]}
                />
                <mesh
                    geometry={nodes.mesh372063805_8.geometry}
                    material={materials["mat19.001"]}
                />
            </group>
            <group
                position={[-0.074, 0, -1.521]}
                rotation={[0, -Math.PI / 2, 0]}
            >
                <mesh
                    geometry={nodes.Plane001_Plane002_BlackWood001.geometry}
                    material={materials["BlackWood.001"]}
                />
                <mesh
                    geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry}
                    material={materials["BlackCoatSteel.001"]}
                />
                <mesh
                    geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry}
                    material={materials["GrayPlastic.001"]}
                />
                <mesh
                    geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry}
                    material={materials["WhiteSteelScrew.001"]}
                />
                <mesh
                    geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry}
                    material={materials["BlackPlastic.001"]}
                />
            </group>
            <group position={[-0.868, 1.694, -2.038]}>
                <mesh
                    geometry={nodes.SM_ShelfSM_Shelf1_1.geometry}
                    material={materials.lambert2SG}
                />
                <mesh
                    geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry}
                    material={materials["795548.001"]}
                />
            </group>
            <group position={[-1.302, 2.071, -1.986]}>
                <mesh
                    geometry={nodes["Node-Mesh001"].geometry}
                    material={materials.lambert4SG}
                />
                <mesh
                    geometry={nodes["Node-Mesh001_1"].geometry}
                    material={materials["lambert2SG.001"]}
                />
                <mesh
                    geometry={nodes["Node-Mesh001_2"].geometry}
                    material={materials["lambert3SG.002"]}
                />
            </group>
            <mesh
                geometry={nodes.WawaRug.geometry}
                material={materials.Rug}
                position={[0.358, 0.009, 0.765]}
            />
            <group position={[-0.044, 0.981, -1.346]} rotation={[0, -0.165, 0]}>
                <mesh
                    geometry={nodes.mesh425587018.geometry}
                    material={materials["mat21.004"]}
                />
                <mesh
                    geometry={nodes.mesh425587018_1.geometry}
                    material={materials["mat22.001"]}
                />
                <mesh
                    geometry={nodes.mesh425587018_2.geometry}
                    material={materials["mat9.002"]}
                />
                <mesh
                    geometry={nodes.mesh425587018_3.geometry}
                    material={materials["mat16.001"]}
                />
            </group>
            <group
                position={[0.454, 0.939, -1.604]}
                rotation={[Math.PI, -1.099, Math.PI]}
            >
                <mesh
                    geometry={nodes.iMac_1.geometry}
                    material={materials.Screen}
                />
                <mesh
                    geometry={nodes.iMac_1_1.geometry}
                    material={materials.ScreenBlack}
                />
                <mesh
                    geometry={nodes.iMac_1_2.geometry}
                    material={materials.iMacBody}
                />
            </group>
            <mesh
                geometry={nodes.Comp_Mouse.geometry}
                material={materials["lambert3SG.003"]}
            />
            <group
                position={[-0.894, 0.943, -1.677]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.31}
            >
                <mesh
                    geometry={nodes.Houseplant_7_1.geometry}
                    material={materials["Black.001"]}
                />
                <mesh
                    geometry={nodes.Houseplant_7_2.geometry}
                    material={materials["Brown.001"]}
                />
                <mesh
                    geometry={nodes.Houseplant_7_3.geometry}
                    material={materials["Plant_Green.001"]}
                />
            </group>
            <group position={[-0.278, 0, -0.708]} rotation={[0, -0.376, 0]}>
                <mesh
                    geometry={nodes["Node-Mesh"].geometry}
                    material={materials.Office_Cha}
                />
                <mesh
                    geometry={nodes["Node-Mesh_1"].geometry}
                    material={materials.Office_Cha_1}
                />
            </group>
            <group position={[-2.438, 1.073, -1.323]} rotation={[0, -1.571, 0]}>
                <mesh
                    geometry={nodes.mesh1308063879.geometry}
                    material={materials["mat14.001"]}
                />
                <mesh
                    geometry={nodes.mesh1308063879_1.geometry}
                    material={materials.mat20}
                />
                <mesh
                    geometry={nodes.mesh1308063879_2.geometry}
                    material={materials["mat13.001"]}
                />
                <mesh
                    geometry={nodes.mesh1308063879_3.geometry}
                    material={materials["mat11.001"]}
                />
                <mesh
                    geometry={nodes.mesh1308063879_4.geometry}
                    material={materials.mat9}
                />
                <mesh
                    geometry={nodes.mesh1308063879_5.geometry}
                    material={materials.mat10}
                />
                <mesh
                    geometry={nodes.mesh1308063879_6.geometry}
                    material={materials.mat8}
                />
                <mesh
                    geometry={nodes.mesh1308063879_7.geometry}
                    material={materials.mat0}
                />
                <mesh
                    geometry={nodes.mesh1308063879_8.geometry}
                    material={materials.mat12}
                />
                <mesh
                    geometry={nodes.mesh1308063879_9.geometry}
                    material={materials.mat18}
                />
                <mesh
                    geometry={nodes.mesh1308063879_10.geometry}
                    material={materials.mat19}
                />
                <mesh
                    geometry={nodes.mesh1308063879_11.geometry}
                    material={materials.mat22}
                />
                <mesh
                    geometry={nodes.mesh1308063879_12.geometry}
                    material={materials.mat15}
                />
                <mesh
                    geometry={nodes.mesh1308063879_13.geometry}
                    material={materials.mat23}
                />
                <mesh
                    geometry={nodes.mesh1308063879_14.geometry}
                    material={materials.mat16}
                />
                <mesh
                    geometry={nodes.mesh1308063879_15.geometry}
                    material={materials.mat3}
                />
                <mesh
                    geometry={nodes.mesh1308063879_16.geometry}
                    material={materials.mat17}
                />
                <mesh
                    geometry={nodes.mesh1308063879_17.geometry}
                    material={materials.mat5}
                />
                <mesh
                    geometry={nodes.mesh1308063879_18.geometry}
                    material={materials.mat6}
                />
            </group>
            <mesh
                geometry={nodes.Black_Cat.geometry}
                material={materials.blinn5SG}
                position={[-0.752, 0.955, -1.362]}
                rotation={[-1.545, 0.11, -1.8]}
                scale={0.001}
            />
            <group position={[-0.171, 0.969, -1.811]} scale={0.152}>
                <mesh
                    geometry={nodes.mesh256948792.geometry}
                    material={materials["mat16.002"]}
                />
                <mesh
                    geometry={nodes.mesh256948792_1.geometry}
                    material={materials["mat23.002"]}
                />
                <mesh
                    geometry={nodes.mesh256948792_2.geometry}
                    material={materials["mat17.001"]}
                />
                <mesh
                    geometry={nodes.mesh256948792_3.geometry}
                    material={materials.mat25}
                />
                <mesh
                    geometry={nodes.mesh256948792_4.geometry}
                    material={materials["mat15.001"]}
                />
            </group>
            <mesh
                geometry={nodes.Plane001.geometry}
                material={materials.Floor}
            />
            <mesh
                geometry={nodes.Plane001_1.geometry}
                material={materials.White}
            />
            <mesh
                geometry={nodes.Plane001_2.geometry}
                material={materials.Wall}
            />
            <mesh
                geometry={nodes.Plane001_3.geometry}
                material={materials.Glass}
            />
        </group>
    );
}

useGLTF.preload("models/roomnew.glb");
